// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtgLu4A7R5LKopUjGK81DSDP5XuL27qe4',
    appId: '1:973225421152:web:d01d529d224c839ec71605',
    messagingSenderId: '973225421152',
    projectId: 'sanbercode-firebase',
    authDomain: 'sanbercode-firebase.firebaseapp.com',
    storageBucket: 'sanbercode-firebase.firebasestorage.app',
    measurementId: 'G-0YLEKKVNYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPCqaaC7AIzA8bcre1zItxWTJIIHDMuwI',
    appId: '1:973225421152:android:b1d642eb5127914ac71605',
    messagingSenderId: '973225421152',
    projectId: 'sanbercode-firebase',
    storageBucket: 'sanbercode-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQGTiU7YsW5DYucbgwL0Yy6SzcU3iRdZM',
    appId: '1:973225421152:ios:d4eaf8ae75a7d8b9c71605',
    messagingSenderId: '973225421152',
    projectId: 'sanbercode-firebase',
    storageBucket: 'sanbercode-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQGTiU7YsW5DYucbgwL0Yy6SzcU3iRdZM',
    appId: '1:973225421152:ios:d4eaf8ae75a7d8b9c71605',
    messagingSenderId: '973225421152',
    projectId: 'sanbercode-firebase',
    storageBucket: 'sanbercode-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtgLu4A7R5LKopUjGK81DSDP5XuL27qe4',
    appId: '1:973225421152:web:a48100019657de01c71605',
    messagingSenderId: '973225421152',
    projectId: 'sanbercode-firebase',
    authDomain: 'sanbercode-firebase.firebaseapp.com',
    storageBucket: 'sanbercode-firebase.firebasestorage.app',
    measurementId: 'G-D05CJ96KZT',
  );
}
